Add _get_vars() with checks

diff --git a/tty-colorscheme/tty-colorscheme b/tty-colorscheme/tty-colorscheme
--- a/tty-colorscheme/tty-colorscheme
+++ b/tty-colorscheme/tty-colorscheme
@@ -18,6 +18,28 @@ _set_colors() {
         "${color13:?}" "${color14:?}" "${color15:?}" "${color16:?}"
 }
 
+_get_vars() {
+    while IFS="" read -r line || [[ -n "${line}" ]]; do
+        # Skip empty lines and comments
+        [[ -z "${line}" || "${line}" =~ ^[[:space:]]*# ]] && continue
+
+        # Check string format and HEX value
+        if [[ ! "${line}" =~ ^color(0[1-9]|1[0-6])=\"[0-9A-Fa-f]{6}\"$ ]]; then
+            printf "Invalid color format in %s\n%s\n" "${1}" "${line}"
+            exit 1
+        fi
+
+        # Assign variables
+        if ! [[ "${line}" =~ ^(color(0[1-9]|1[0-6]))=\"([0-9A-Fa-f]{6})\"$ ]]; then
+            printf "Failed to parse line from %s\n%s\n" "${1}" "${line}"
+            exit 1
+        fi
+
+        declare -g "${BASH_REMATCH[1]}=${BASH_REMATCH[3]}"
+
+    done < "${cs_dir}/${1}"
+}
+
 _fnt_warn() {
     [[ -z "${fnt_arr:-}" ]] && printf "No PSF fonts found\n"
 }
@@ -176,7 +198,7 @@ cs_set_scheme() {
         exit 1
     fi
 
-    source "${cs_dir}/${1}"
+    _get_vars "${1}"
 
     if [[ "$(id -u)" -eq 0 ]]; then
         for i in {1..6}; do
