tty-colorscheme: stderr redirects

diff --git a/tty-colorscheme/tty-colorscheme b/tty-colorscheme/tty-colorscheme
--- a/tty-colorscheme/tty-colorscheme
+++ b/tty-colorscheme/tty-colorscheme
@@ -19,7 +19,7 @@ _set_colors() {
 }
 
 _fnt_warn() {
-    [[ -z "${fnt_arr:-}" ]] && printf "No PSF fonts found\n"
+    [[ -z "${fnt_arr:-}" ]] && printf "No PSF fonts found\n" >&2
 }
 
 _get_fonts() { # Only output file name
@@ -57,7 +57,7 @@ _set_font() {
 }
 
 _cs_warn() {
-    [[ -z "${cs_arr:-}" ]] && printf "No colorschemes found\n"
+    [[ -z "${cs_arr:-}" ]] && printf "No colorschemes found\n" >&2
 }
 
 _get_schemes() { # Only output file name
@@ -177,7 +177,7 @@ cs_cycle() {
 
 cs_set_scheme() {
     if [[ ! -f "${cs_dir}/${1}" ]]; then
-        printf "Invalid colorscheme: %s\n" "${1}"
+        printf "Invalid colorscheme: %s\n" "${1}" >&2
         exit 1
     fi
 
@@ -186,7 +186,7 @@ cs_set_scheme() {
             declare -g "${BASH_REMATCH[1]}=${BASH_REMATCH[3]}"
         else
             [[ -z "${line}" || "${line}" =~ ^[[:space:]]*# ]] && continue
-            printf "Invalid color format: %s in %s\n" "${line}" "${1}"
+            printf "Invalid color format: %s in %s\n" "${line}" "${1}" >&2
             exit 1
         fi
     done < "${cs_dir}/${1}"
@@ -216,7 +216,7 @@ cs_print_help() {
     printf "  -c    Cycle through colorschemes and fonts\n"
 
     if ! tty | grep -q tty; then
-        printf "%s should be run from TTY\n" "$(basename "${0}")"
+        printf "%s should be run from TTY\n" "$(basename "${0}")" >&2
     fi
 }
 
@@ -239,7 +239,7 @@ while getopts ":lfpc" opt; do
             exit 0
             ;;
         *)
-            printf "Invalid option: -%s\n" "${OPTARG}"
+            printf "Invalid option: -%s\n" "${OPTARG}" >&2
             cs_print_help
             exit 1
             ;;
